### ISSUE TITLE
Question: Any Tyescript custom types support?

### ISSUE THREAD

**Issue by viT-1** [abritinthebay/jest-tobetype#12]
And why your module haven't @types/jest-tobetype package?

**Comment by abritinthebay** [comment]
Why would it? This is a library for adding support to Jest for testing Javascript types.  All it does is extend Jest. There is no way in JS to test TS types (and there never will be, they're part of TS) and there are no types for this to add to a @types package.

Long story short: no, and because it's not needed or possible.

**Comment by viT-1** [comment]
@abritinthebay Thank you for explanation.
